### PR TITLE
Headless Chrome installation instructions

### PR DESCRIPTION
**Pull request by aitbw**
References
==========
* Related PRs: consul/consul#2534, AyuntamientoMadrid/consul#1387

Objectives
==========
Updated documentation to include ChromeDriver as a prerequisite for running tests as well as installation instructions for Mac OS and Linux in both :gb: and :es:

### CODE REVIEW

**Comment by mlovic** [comment]
Chrome/chromium also requires the `libnss3` package on Debian (this comes already installed with Ubuntu).

**Comment by aitbw** [comment]
But shouldn't that package be automatically installed along with Chrome/Chromium, @mlovic? :thinking:

**Comment by mlovic** [comment]
@aitbw The "apt" chromium package does not list it as a dependency, but when I tried running chromium (or chromedriver maybe?) on the standard Debian Docker image, I remember it would give me a runtime error. This was a while ago though, I can't remember exactly, I'll try to reproduce the error and make sure.

**Comment by voodoorai2000** [comment]
Awesome!

**Pull request merged**
