### PR TITLE
Fix broken link on translations page

### PR DESCRIPTION
**Pull request by maxstevens-nl**
Links which contain spaces need to be escaped

### CODE REVIEW

**Comment by taitus** [comment]
Hi @markusgeert 

Thanks for the PR. Nice catch 👏 

Indeed, it seems that the link in the [documentation](https://docs.consulproject.org/docs/english-documentation/customization/translations) doesn't show correctly.

To add this PR, could you add the same change to the Spanish file?
`es/customization/translations.md`

Thanks!

**Comment by maxstevens-nl** [comment]
> To add this PR, could you add the same change to the Spanish file?

@taitus sure, I don't really have time to do that right now, but in 1 or 2 weeks I can take a look. If you're up to change it that's also fine with me. I can give you edit privileges to my fork if you want.

**Comment by javierm** [comment]
@markusgeert We're about to make this repository read-only since from now on we'll be using [our GitBook page](https://docs.consuldemocracy.org/tech_docs/) to do the changes. I've already submitted a "change request" there in order to change the link (thanks a lot for the contribution! :pray:).

So I'm closing this pull request as well as the other open pull requests.

**Comment by javierm** [comment]
The changes have now been applied :smile:.

**Pull request closed without merging**
